### ISSUE TITLE
Add changelog to releases

### ISSUE THREAD

**Issue by florianmutter** [bufbuild/buf-setup-action#211]
It would be very helpful if the release would contain a change log. This would make updating the action way easier and avoid unexpected changes from being applied and breaking pipelines.

**Comment by nicksnyder** [comment]
This GitHub action just follows the releases for the Buf CLI, so the relevant changelog is here:
https://github.com/bufbuild/buf/blob/main/CHANGELOG.md

We did [release some big improvements to the Buf CLI recently](https://buf.build/blog/buf-cli-next-generation), but we took many steps to ensure backward compatibility. If you are having compatibility issues, please report them in https://github.com/bufbuild/buf and we can investigate.

Going to close this issue since we don't plan on having a separate CHANGELOG for this action.

**Comment by florianmutter** [comment]
Good to know. My suggestion is then to copy the changelog of buf cli into the buf action release
