### ISSUE TITLE
install/document protoc dependency

### ISSUE THREAD

**Issue by jzelinskie** [bufbuild/buf-setup-action#3]
The C-based gRPC protoc plugins still require protoc and not only buf's compiler, thus this Action should support installing protoc or at least have a documented way to do so.

I'm using https://github.com/arduino/setup-protoc

Users will also probably need the gRPC plugins, so installing gRPC seems equally important.

**Comment by amckinney** [comment]
Thanks for the issue! I apologize for the delayed response here - this issue got last in the stack and I didn't notice it again until today.

You're right, we at least need to mention this in the action's `README.md`, or some other place in https://docs.buf.build (or both). I hesitate to build out some sort of configurable option for installing `protoc` in `buf-setup-action` since we actually plan to host the plugins built-in to `protoc` ourselves someday (ideally sooner rather than later). That way, users won't need to install `protoc`, and they can rely on the specific plugins themselves, and `buf-setup-action` won't have to carry around a deprecated configuration field for its lifetime.

Anyway, we'll follow-up with some documentation, and (probably) recommend the same action you referenced above to get people going. Thanks for the suggestion!
